# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: wcbot
build:
  main: ./cmd/wcbot/
  binary: wcbot
  env:
    - CGO_ENABLED=0
  ldflags:
    -s -w -X main.Version={{.Version}} -X main.GitCommit={{.ShortCommit}} -X main.BuildDate={{.Date}}`.
  goos:
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  wrap_in_directory: true
  replacements:
    amd64: 64bit
    386: 32bit
    arm: arm
    arm64: arm64
    darwin: macos
    linux: linux
    #windows: windows
  files:
    - LICENSE.txt
    - README.md
    - CHANGELOG.md
    - godownloader-wcbot.sh
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
sign:
  artifacts: checksum
snapshot:
  name_template: '{{ .ProjectName }}_SNAPSHOT_{{ .Commit }}'   
#changelog:
#  sort: asc
#  filters:
#    exclude:
#    - '^docs:'
#    - '^test:'
release:
  draft: true
  prerelease: true
  disable: false
