# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
    - CGO_ENABLED=0
  - goos:
    - linux
    - darwin
  - goarch:
    - 386
    - amd64
    - arm
    - arm64
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  wrap_in_directory: true
  replacements:
    darwin: Darwin
    linux: Linux
    #windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
sign:
  artifacts: checksum
snapshot:
  name_template: '{{ .ProjectName }}_SNAPSHOT_{{ .Commit }}'   
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true
  prerelease: true
  disable: false