# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: wcbot
build:
  main: cmd/wcbot/main.go
  binary: wcbot
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  wrap_in_directory: true
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    #windows: Windows
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}_checksums.txt'
sign:
  artifacts: checksum
snapshot:
  name_template: '{{ .ProjectName }}_SNAPSHOT_{{ .Commit }}'   
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  draft: true
  prerelease: true
  disable: false
