language: go

sudo: false

go:
  - "1.10"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover


notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  
script:
  - go test ./...
  - $GOPATH/bin/goveralls -service=travis-ci
  